Use CWD(current working directory for tasks.)
eclipse/che-theia-task-plugin pull request #21
Opened 2019-03-18 07:48 UTC by AndrienkoAleksandr

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

2019-03-21 09:47 UTC, RomanNikitenko approved these changes

2019-03-21 09:47 UTC, RomanNikitenko commented on che-theia-task-extension/src/node/che-task-runner.ts
> +
As I can see we don't use this const in another places, so you can just pass `taskConfig.target.workingDir.` But up to you.

2019-03-21 11:30 UTC, azatsarynnyy approved these changes

2019-03-22 15:26 UTC, mmorhun approved these changes

2019-03-22 15:29 UTC, evidolob requested changes
As IDE 1 team merged task plugin in che-theia repository, this changes should be for that plugin, and this repository should be deprecated

2019-03-22 15:43 UTC, AndrienkoAleksandr commented
Ok, I closed it, make sense this one: https://github.com/eclipse/che-theia/pull/116

2019-03-29 13:23 UTC, evidolob approved these changes

2019-03-29 18:30 UTC, merged